/**
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package apis.petstore.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param petId 
 * @param quantity 
 * @param shipDate 
 * @param status Order Status
 * @param complete 
 */

data class Order (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("petId")
    val petId: kotlin.Long? = null,

    @SerializedName("quantity")
    val quantity: kotlin.Int? = null,

    @SerializedName("shipDate")
    val shipDate: java.time.OffsetDateTime? = null,

    /* Order Status */
    @SerializedName("status")
    val status: Order.Status? = null,

    @SerializedName("complete")
    val complete: kotlin.Boolean? = null

) {

    /**
     * Order Status
     *
     * Values: placed,approved,delivered
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "placed") placed("placed"),
        @SerializedName(value = "approved") approved("approved"),
        @SerializedName(value = "delivered") delivered("delivered");
    }
}